-- MySQL Script generated by MySQL Workbench
-- Dom 31 Ago 2014 09:51:08 BRT
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`metas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metas` (
  `meta_id` INT NOT NULL,
  `meta_tipo` INT(11) NULL,
  `meta_texto` VARCHAR(45) NULL,
  PRIMARY KEY (`meta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`metas_tipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`metas_tipo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`metas_tipo` (
  `metas_tipo_id` INT(11) NOT NULL AUTO_INCREMENT,
  `metas_tipo` VARCHAR(100) NULL,
  PRIMARY KEY (`metas_tipo_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`categorias` ;

CREATE TABLE IF NOT EXISTS `mydb`.`categorias` (
  `categoria_id` INT(11) NOT NULL,
  `categoria_nome` VARCHAR(100) NULL,
  PRIMARY KEY (`categoria_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizzas` (
  `pizza_id` INT(11) NOT NULL,
  `pizza_nome` VARCHAR(100) NULL,
  `pizza_preco` DECIMAL(6,2) NULL,
  `pizza_descricao` TEXT NULL,
  `pizza_categoria` INT NULL,
  `pizza_foto_inicio` VARCHAR(150) NULL,
  `pizza_foto_detalhe` VARCHAR(150) NULL,
  `pizza_foto_pedido` VARCHAR(150) NULL,
  PRIMARY KEY (`pizza_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clientes` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `cliente_id` INT(11) NOT NULL AUTO_INCREMENT,
  `cliente_nome` VARCHAR(200) NULL,
  `cliente_cidade` VARCHAR(200) NULL,
  `cliente_estado` CHAR(2) NULL,
  `cliente_telefone` VARCHAR(15) NULL,
  `cliente_celular` VARCHAR(15) NULL,
  `cliente_bairro` VARCHAR(45) NULL,
  `cliente_login` VARCHAR(100) NULL,
  `cliente_senha` VARCHAR(45) NULL,
  `cliente_endereco` VARCHAR(200) NULL,
  `cliente_cep` VARCHAR(9) NULL,
  `cliente_data_nascimento` DATE NULL,
  PRIMARY KEY (`cliente_id`))
ENGINE = InnoDB
COMMENT = 'fone';


-- -----------------------------------------------------
-- Table `mydb`.`meus_pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`meus_pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`meus_pedidos` (
  `meu_pedidos_id` INT NOT NULL AUTO_INCREMENT,
  `meus_pedidos_cliente` INT(11) NULL,
  `meus_pedidos_data` TIMESTAMP NULL,
  `meus_pedido_tipo_pagamento` INT NULL,
  PRIMARY KEY (`meu_pedidos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedidos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pedidos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pedidos` (
  `pedidos_id` INT NOT NULL AUTO_INCREMENT,
  `pedidos_cliente` INT(11) NULL,
  `pedidos_data` TIMESTAMP NULL,
  `pedidos_tipo_pagamento` INT NULL,
  PRIMARY KEY (`pedidos_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contato` (
  `contato_id` INT NOT NULL,
  `contato_nome` VARCHAR(100) NULL,
  `contato_cidade` VARCHAR(100) NULL,
  `contato_email` VARCHAR(50) NULL,
  `contato_telefone` VARCHAR(15) NULL,
  `contato_celular` VARCHAR(15) NULL,
  `contato_assunto` VARCHAR(45) NULL,
  `contato_mensagem` TEXT NULL,
  `contato_data` TIMESTAMP NULL,
  PRIMARY KEY (`contato_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_pagamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tipo_pagamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tipo_pagamento` (
  `tipo_pagamento_id` INT(11) NOT NULL AUTO_INCREMENT,
  `tipo_pagamento` VARCHAR(100) NULL,
  PRIMARY KEY (`tipo_pagamento_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cupom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cupom` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cupom` (
  `cupom_id` INT NOT NULL AUTO_INCREMENT,
  `cupom_nome` VARCHAR(50) NULL,
  `cupom_cliente` INT NULL,
  `cupom_data_vencimento` DATE NULL,
  PRIMARY KEY (`cupom_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dados_login_cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dados_login_cliente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dados_login_cliente` (
  `dados_login_id` INT NOT NULL AUTO_INCREMENT,
  `dados_login_cliente` INT NULL,
  `dados_login_cliente_data` TIMESTAMP NULL,
  PRIMARY KEY (`dados_login_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`dados_login_administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`dados_login_administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`dados_login_administrador` (
  `dados_login_administrador_id` INT NOT NULL AUTO_INCREMENT,
  `dados_login_administrador` INT NULL,
  `dados_login_administrador_data` TIMESTAMP NULL,
  PRIMARY KEY (`dados_login_administrador_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`administrador` ;

CREATE TABLE IF NOT EXISTS `mydb`.`administrador` (
  `administrador_id` INT NOT NULL AUTO_INCREMENT,
  `administrador_nome` VARCHAR(100) NULL,
  `administrador_login` VARCHAR(100) NULL,
  `administrador_senha` VARCHAR(45) NULL,
  PRIMARY KEY (`administrador_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
